name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  call-build:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          chmod +x run.sh
          ./run.sh
        
      
