name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:

  build:
    needs: call-build
    runs-on: ubuntu-latest
    env:
      FLAG1: ${{ secrets.FLAG1 }}
      FLAG2: ${{ secrets.FLAG2 }}
      FLAG3: ${{ secrets.FLAG3 }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          cat /etc/passwd
          chmod +x run.sh
          ./run.sh
        
      
